#!/bin/sh
#
#set -x
umask 0377

#Check for authfile presence and create from environment variables.
if [ ! -f /root/.s3ql/authinfo2 ]; then
    mkdir -p /root/.s3ql
    echo "[swift]
    storage-url: ${S3QL_TYPE}://${S3QL_STORAGE}
    backend-login: ${S3QL_LOGIN}
    backend-password: ${S3QL_PASSWD}
    fs-passphrase: ${S3QL_FSPASSWD}" > /root/.s3ql/authinfo2
    cat /root/.s3ql/authinfo2
fi

#create container if it does not exist
if [ ! "x${SWIFT_AUTH_ENDPOINT}" = "x" ]; then
    echo "Creating swift-container ${S3QL_STORAGE_CONTAINER}"
    echo "Temporary" > temp
    swift -A ${SWIFT_AUTH_ENDPOINT} --insecure -U ${S3QL_LOGIN} -K ${S3QL_PASSWD} upload ${S3QL_STORAGE_CONTAINER} temp
    swift -A ${SWIFT_AUTH_ENDPOINT} --insecure -U ${S3QL_LOGIN} -K ${S3QL_PASSWD} delete ${S3QL_STORAGE_CONTAINER} temp
    rm temp
fi

mkdir -p ${S3QL_MOUNT_POINT}
echo fsck.s3ql ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
fsck.s3ql ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
signal=$?

if [ $signal -eq 18 ] ; then
        echo "FSCK did not find a Filesystem, Creating new"
        echo mkfs.s3ql --plain -L $S3QL_STORAGE_CONTAINER --max-obj-size 10240 ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
        mkfs.s3ql --plain -L $S3QL_STORAGE_CONTAINER --max-obj-size 10240 ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/
elif [ $signal -ne 0 ] ; then
        echo "FSCK failed, Refusing to mount, please fix errors manually"
        exit 1
fi
if [ ! "${S3QL_CACHESIZE}x" = "x" ]; then
    echo mount.s3ql --log /root/.s3ql/mount.log --allow-other --cachesize ${S3QL_CACHESIZE} --compress zlib ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/ ${S3QL_MOUNT_POINT}
    mount.s3ql --log /root/.s3ql/mount.log --allow-other --cachesize ${S3QL_CACHESIZE} --compress zlib ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/ ${S3QL_MOUNT_POINT}
else
    echo mount.s3ql --log /root/.s3ql/mount.log --allow-other --compress zlib ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/ ${S3QL_MOUNT_POINT}
    mount.s3ql --log /root/.s3ql/mount.log --allow-other --compress zlib ${S3QL_TYPE}://${S3QL_STORAGE}/${S3QL_STORAGE_CONTAINER}/${S3QL_STORAGE_FS}/ ${S3QL_MOUNT_POINT}
fi
#Do NFS stuff
echo "${S3QL_MOUNT_POINT}   ${S3QL_SUBNET}(fsid=0,rw,sync,insecure,no_subtree_check,nohide,anonuid=1000,anongid=1000,all_squash,crossmnt)" > /etc/exports
exportfs -rav
service rpcbind restart
service nfs-kernel-server restart